spring:
  application:
    name: health-reset-plan-cloud
  profiles:
    active: dev,local
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: deletedAt
      logic-delete-value: NOW()
      logic-not-delete-value: 'NULL'

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    io.healthresetplan: INFO
    org.springframework.security: INFO
